apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: abhishek-joshi-flask-app-hpa
  namespace: default  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: abhishek-joshi-flask-app  # Name of your deployment
  minReplicas: 3  # Minimum number of pods
  maxReplicas: 10  # Maximum number of pods (you can adjust this based on your needs)
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60  # Target average CPU utilization (60%)